version: 2.1

jobs:
  build:
    docker:
      - image: ruby:2.7

    working_directory: ~/gymApp

    steps:
      - checkout

      - run:
          name: Print Hello, World!
          command: echo "Hello, World!"

workflows:
  version: 2
  build:
    jobs:
      - build
