version: 2.1

jobs:
  build:
    docker:
      - image: ruby:2.7

    working_directory: ~/gymApp

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install

      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build
