version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            bundle install

      - run:
          name: Run tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build


